import os

from dotenv import load_dotenv
from datetime import datetime

from discord import Message
from supabase import Client, create_client
from functions.utils import calculate_next_recurring
from functions.extraction import Reminder, RecurringReminder, RecurringReminderExtraction

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)


def save_message(message: Message):
    """
    Insert a Discord message into Supabase

    Args:
        message: Discord message object

    Returns:
        Supabase API response object from inserting message
    """
    data = {
        "message_id": message.id,
        "channel_id": message.channel.id,
        "author_id": message.author.id,
        "author_name": message.author.name,
        "content": message.content,
        "created_at": message.created_at.isoformat(),
    }

    return (
        supabase
        .table("messages")
        .insert(data)
        .execute()
    )

def save_reminder(reminder: Reminder, message: Message):
    """
    Insert reminder and message into Supabase

    Args:
        reminder: Reminder object
        message: Discord message object associated with the reminder

    Returns:
        Supaase API response object from inserting the reminder
    """
    # save_message() and retain id for fk relation
    response = save_message(message)
    message_id = response.data[0]["id"]

    # fill in year, month, and day fields for easier querying later
    if reminder.range_start:
        reminder.year = reminder.range_start.year
        reminder.month = reminder.range_start.month
        reminder.day = reminder.range_start.day    

    # Need to use .model_dump() as json
    # Fill in message_id and author_id
    data = reminder.model_dump(mode="json")
    data["message_id"] = message_id
    data["author_id"] = message.author.id

    return (
        supabase
        .table("reminders")
        .insert(data)
        .execute()
    )

def save_recurring(recurring_reminder_extraction: RecurringReminderExtraction, message: Message):
    """
    Inserts RecurringReminderExtraction and message into Supabase. Calls generate_next_reminder() to handle the individual reminder associated with the recurrence

    Args:
        recurring_reminder_extraction: RecurringReminderExtraction object
        message: Discord message object

    Returns:
        Supabase API response object from inserting into recurring_reminders table
    """
    # save_message() and retain id for fk relation
    response = save_message(message)
    message_id = response.data[0]["id"]

    # Create a RecurringReminder object to pass into calculate_next_recurring()
    # next_reminder initialized as None but will be generated by the function
    # Function uses last_reminder_date so we fill it in with start_date for now
    recurring_reminder = RecurringReminder(
        **recurring_reminder_extraction.model_dump(),
        reminder_id = None,
        message_id = message_id,
        author_id = message.author.id,
        last_reminder_date = recurring_reminder_extraction.start_date,
        next_reminder = None
    )

    # Replace next_reminder with the correct next_reminder
    recurring_reminder.next_reminder = calculate_next_recurring(recurring_reminder)

    # Generate or update the individual reminder associated with recurrence
    response = generate_next_reminder(recurring_reminder)

    # Store and fill in id of the generated reminder
    reminder_id = response.data[0]["id"]
    recurring_reminder.reminder_id = reminder_id

    # Prepare to insert into Supabase
    data = recurring_reminder.model_dump(mode="json")

    return (
        supabase    
        .table("recurring_reminders")
        .insert(data)
        .execute()
    )

def generate_next_reminder(recurring_reminder: RecurringReminder):
    """
    Generates and inserts the indivudal reminder associated with a recurrence, or updates it if it already exists

    Args:
        recurring_reminder: RecurringReminder object

    Returns: Supabase API response object from either updating or inserting the reminder
    """
    # Check if reminder already exists, in this case update it
    if recurring_reminder.reminder_id:
        response = (
            supabase
            .table("reminders")
            .select("id")
            .eq("id", recurring_reminder.reminder_id)
            .execute()
        )

        if response.data:
            return (
                supabase
                .table("reminders")
                .update({
                    "year": recurring_reminder.next_reminder.year,
                    "month": recurring_reminder.next_reminder.month,
                    "day": recurring_reminder.next_reminder.day,
                    "hour": recurring_reminder.next_reminder.hour,
                    "minute": recurring_reminder.next_reminder.minute,
                })
                .eq("id", recurring_reminder.reminder_id)
                .execute()
            )

    # Generate the reminder from the recurrence
    reminder = {
        "message_id": recurring_reminder.message_id,
        "author_id": recurring_reminder.author_id,
        "title": recurring_reminder.title,
        "year": recurring_reminder.next_reminder.year,
        "month": recurring_reminder.next_reminder.month,
        "day": recurring_reminder.next_reminder.day,
        "hour": recurring_reminder.next_reminder.hour,
        "minute": recurring_reminder.next_reminder.minute,
        "reminder_type": "recurring",
    }

    return (
        supabase
        .table("reminders")
        .insert(reminder)
        .execute()
    )

def fetch_recent(channel: int):
    """
    Debug function to retrieve the 5 most recently stored messages

    Args:
        channel: Discord channel id

    Returns:
        Supabase API response object from retrieving the last 5 messages
    """
    return (
        supabase
        .table("messages")
        .select("author_name, content, created_at")
        .eq("channel_id", channel)
        .order("created_at", desc=True)
        .limit(5)
        .execute()
    )

def fetch_reminders(user_id: int):
    """
    Retrieves all of a user's reminders, sorted by time to be used for process_reminders()

    Args:
        user_id: Discord user id
    
    Returns:
        Supabase API response object of all reminders associated with a Discord user id, sorted by time
    """
    return (
        supabase
        .table("reminders")
        .select("*")
        .eq("author_id", user_id)
        .order("year")
        .order("month")
        .order("day")
        .order("hour")
        .order("minute")
        .execute()
    )

def fetch_recurring_updates(now: datetime):
    """
    Helper function fetching active outdated recurring reminders to be processed by update_recurring()

    Args:
        now: datetime object representing the current time

    Returns:
        Supabase API response object from fetching all active outdated reminders
    """
    return (
        supabase
        .table("recurring_reminders")
        .select("*")
        .eq("active", True)
        .lte("next_reminder", now.isoformat())
        .execute()
    )

def update_recurring(now: datetime) -> None:
    """
    Updates outdated reminders associated with recurrences, to be used by tasks.loop

    Args:
        now: datetime object representing the current time

    Returns:
        None
    """
    outdated_recurring_reminders = fetch_recurring_updates(now)

    # Loop through each outdated reminder and handle them individually
    for recurring_reminder_dict in outdated_recurring_reminders.data:
        # Create a RecurringReminder object from the outdated reminder
        recurring_reminder = RecurringReminder(**recurring_reminder_dict)

        # Find the next valid occurence
        next_reminder = calculate_next_recurring(recurring_reminder)

        # Update the recurring_reminder's fields in Supabase
        (
            supabase
            .table("recurring_reminders")
            .update({
                "next_reminder": next_reminder.isoformat(),
                "last_reminder_date": recurring_reminder.next_reminder.date().isoformat(),
            })
            .eq("reminder_id", recurring_reminder.reminder_id)
            .execute()
        )

        # Update the local RecurringReminder object's next_reminder attribute so we can update the individual reminder
        recurring_reminder.next_reminder = next_reminder
        generate_next_reminder(recurring_reminder)

    print("Finished updating recurring reminders")

def delete_recurring(reminder_id: int):
    """
    Helper function to delete from recurring_reminders table, to be used with delete_reminder()

    Args:
        reminder_id: ID associated with the individual reminder
    
    Returns: Supabase API response object from deleting the recurring reminder
    """
    return (
        supabase
        .table("recurring_reminders")
        .delete()
        .eq("id", reminder_id)
        .execute()
    )

def delete_reminder(reminder_id: int, user_id: int) -> str:
    """
    Deletes a user's reminder, including the recurring_reminder entry and the message entry.

    Args:
        reminder_id: ID of the individual reminder
        user_id: Discord user id

    Returns:
        Result of operation as a string to be sent in the channel for the user to see
    """

    # Check that the reminder ID exists and belongs to the user
    response = (
        supabase
        .table("reminders")
        .select("id, message_id, title, reminder_type")
        .eq("id", reminder_id)
        .eq("author_id", user_id)
        .execute()
    )

    if not response.data:
        return f"Failed to delete reminder #{reminder_id}"

    # Retain the message_id and reminder_type
    reminder = response.data[0]
    message_id = reminder["message_id"]
    reminder_type = reminder["reminder_type"]

    # Check if we need to delete from the recurring_reminders table
    # Must do this first because of FK relations
    if (reminder_type == "recurring"):
        delete_recurring(reminder_id, user_id)

    # Delete individual reminder
    (
        supabase
        .table("reminders")
        .delete()
        .eq("id", reminder_id)
        .execute()
    )

    # Delete message associated with reminder
    (
        supabase
        .table("messages")
        .delete()
        .eq("id", message_id)
        .execute()
    )

    # Return result
    if (reminder_type == "recurring"):
        return f"Successfully deleted recurring reminder associated with #{reminder_id}: {reminder['title']}"
    else:
        return f"Successfully deleted reminder #{reminder_id}: {reminder['title']}"

